### ISSUE TITLE
EOFError: Ran out of input with num_workers>0 in Windows

### ISSUE THREAD

**Issue by msalim86** [KeYang8/WITT#7]
**Hello**
  **I got the below error during the CIFAR10 training. To fix this error, I had to set NUM_DATASET_WORKERS to 0 in datasets.py, which slows down the training time and may affect the reproduction of the code.** 
  **Any suggestion to fix this error with NUM_DATASET_WORKERS = 8 as the original code, please?**
  
  File "train.py", line 150, in train_one_epoch
    for batch_idx, (input, label) in enumerate(train_loader):
  File "C:\Users\Salim\Anaconda3\envs\deepsc_pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 442, in __iter__
    return self._get_iterator()
  File "C:\Users\Salim\Anaconda3\envs\deepsc_pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Salim\Anaconda3\envs\deepsc_pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 1043, in __init__
    w.start()
  File "C:\Users\Salim\Anaconda3\envs\deepsc_pytorch\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Salim\Anaconda3\envs\deepsc_pytorch\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Salim\Anaconda3\envs\deepsc_pytorch\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Salim\Anaconda3\envs\deepsc_pytorch\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Salim\Anaconda3\envs\deepsc_pytorch\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'get_loader.<locals>.worker_init_fn_seed'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Salim\Anaconda3\envs\deepsc_pytorch\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Salim\Anaconda3\envs\deepsc_pytorch\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by KeYang8** [comment]
Sorry, I haven't encountered this situation and can't give a good suggestion.

**Comment by msalim86** [comment]
Thanks a lot for your feedback!
